language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "budgie-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  - npm test # test the code
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: budgie-budget-server
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: aiKbXbAoe2kG38tnMVorHhDqEio7pXathZmdf/+sJ/HtnmD/tKoFyJDlk/If1pS8p0/IiTfEb8Bi0c75S96SGth3BfjU9x0ve37v4EaqbgOJrXz+o664u1Ue14a58bECykgQOSil86d7fnMmEOut4yYfCPREIpHEmW1nC1wdjyEBCFNWCHtZ+KBV19exQgt3MXUbEMQT5iiAIwM4rM4SsPCslFYIRM2qWc+SCOqS6Dw6gSDsFQ4Y0aEs3qEc+kMNr6/68/SKh929qRVEJgZbHKe5vyGWEk7FFippjOO2jC0ZoMXAvJ4F+g3ff6oS5LvQNnOrchn79uR2UATF4A0iqDpYKjbZ5T/hNxCEmidZUzZsE4B2SjBpR6cA7CwACR2md6E8Nlbz2PSfMaqTdiwcDN+6MwjApVUchR/tjLuTUaERJWL6kFvTVaQc9zV6LxwJdj2RLnYbtv0N8iLQbqog6uwA87QTjiWJThm//EkKfDDtTL1aPid8jZi8H18ONV61VjCDi/mfMHLnT3reNep09wgIDD40qrGsqiwvI2kXo+dAJLhC9tT7Q8LZLsJoBDTMIF/6cdrg8d8q1I7ORhRGZufySigQBgeXzXQ5pGyJIaeVsGrasaYHfpxEKF9T9mme65720tM+NQO1i78s0m2m+qG7lkjIZzxea1TZu6ep49s=
